export { default as Sidebar } from './Sidebar'
export { default as NewsletterWidget } from './NewsletterWidget'
export { default as AboutWidget } from './AboutWidget'
export { default as SocialWidget } from './SocialWidget'
export { default as TagsWidget } from './TagsWidget'
export { default as TwitterWidget } from './TwitterWidget'
export { default as SeriesWidget } from './SeriesWidget'
